name: sonarcloud

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
  run:
    shell: pwsh

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Sonar scanner
        run: |
          cd /tmp || exit
          wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          echo "Download completed."
          echo "Unziping downloaded file..."
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          echo "Unzipping completed."
          rm sonar-scanner-cli-5.0.1.3006-linux.zip
          sudo mv sonar-scanner-5.0.1.3006-linux /var/opt
          echo "Creating links..."
          sudo ln -s /var/opt/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner /usr/local/bin/

          echo "Path sonar-scanner:"
          which sonar-scanner
      - name: Build and analyze
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token="${{ secrets.SONAR_TOKEN }}"
      # - name: Install SonarCloud scanner
      #   run: dotnet tool install --global dotnet-sonarscanner --version 6.0.0
      # - name: Build and analyze
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   run: |
      #     dotnet sonarscanner begin /k:"mike74vh_sonarcloud" /o:"mike74vh" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:project.settings="${{ github.workspace }}/src/sonar-project.properties"
      #     dotnet build -c Release
      #     dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      #     echo ">>>>>>>>>>>>>>>>>>>>>>>"
      #     cat ${{ github.workspace }}/src/.sonarqube/out/sonar-project.properties
      #     echo ">>>>>>>>>>>>>>>>>>>>>>>"
      #   working-directory: src
