name: sonarcloud

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
  run:
    shell: pwsh

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SonarCloud scanner
        run: dotnet tool install --global dotnet-sonarscanner --version 6.0.0
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin /k:"mike74vh_sonarcloud" /o:"mike74vh" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build -c Release

          echo ">>>>>>>>>>>>>>>>>>>>>>>"
          cat ${{ github.workspace }}/src/.sonarqube/out/sonar-project.properties
          echo ">>>>>>>>>>>>>>>>>>>>>>>"

          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
        working-directory: src
